# -*- coding: utf-8 -*-
"""Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p3hw9el2y8OveDvbb24FImbAv9nwJefD
"""

import pandas as pd
pd.__version__

from google.colab import drive
drive.mount('/content/drive')





df=pd.read_csv("/content/drive/MyDrive/sana/house.csv")
print(df)

df.describe()

df.min()

df.max()

df.std()

df.sort_values(by='bath')

df.sort_values(by=['bath','area'])

df1=df.sort_values(by=['bath','area'], inplace=True, ascending=[True, False])
print(df1)

df.head()

#slicing

print (df[0:2])

print (df[['area','bath']])

print (df['area'][0:2])

#filtring

print (df [df['bath'] == 2])

print (df [df['area'] != 2000])

#sorting

print (df.sort_values( by ='area'))

df_sorted = df.sort_values( by =['area','bath'])
print(df_sorted)

#filling

print(df.fillna(99))

print(df.fillna(df.mean()))

df1=df[['bath','area']]
print(df1)

df2=df[['2nd floor','area']].fillna(df.min())
print(df2)

df8=df[['2nd floor','area']].fillna(df.max())
print(df8)

df.head()

df.head(2)

df4=df[['saleprice','area']].head(2)
df5=df[['bath','area']].tail(2)
print(df4)
print(df5)

df6=pd.merge(df4,df5)
print(df6)